# Generated by Django 2.1 on 2018-08-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=500)),
                ('Img', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
    ]
